export const KEPERLUAN_OPTIONS = [
  "pecah kk",
  "pindah dalam kota",
  "pindah keluar",
  "keabsahan",
  "legalisir",
  "pengajuan ktp orang asing",
  "perubahan biodata",
  "pemutakhiran gelar",
  "pengajuan KTP",
  "akta kelahiran",
  "akta kematian",
  "akta pengesahan anak",
  "akta perceraian",
  "perubahan biodata (akta kelahiran)",
  "surat ketengaran perjanjian kawin",
  "akta perkawinan",
  "cetak ulang akta",
  "pelaporan kelahiran luar negeri",
  "pelaporan kematian luar negeri",
  "salinan akta kelahiran",
  "perubahan nama akta perkawinan",
  "pelaporan perkawinan luar negri",
  "pengakuan anak",
  "pengangkatan anak",
  "perubahan nama akta perceraian",
  "surat keterangan sudah menikah",
  "perubahan biodata peristiwa penting dengan",
  "surat pertanyaan belum memiliki rumah",
  "surat pernyataan belum pernah menikah",
  "surat pengantar nikah",
  "surat kuasa khusus untuk pembayaran pensiun",
  "surat pernyataan belum meikah lagi bagi janda / duda",
  "surat keterangan izin suami/istri/izin orang tuaatau izin wali (persyaratan pekerja migran)",
  "surat pengantar nikah (untuk perempuan yang akan dipoligami)",
  "surat kuasa penunjukanpelimpahan nomor porsi jemaah haji meninggal dunia",
  "surat pernyataan belum pernah menikah, surat persetujuan orang tua/wali, daftar riwayat hidup untuk pendaftaran sebagai tni",
  "surat pengantar nikah (untuk laki-laki berstatus kawin, yang akan berpoligami)",
  "surat permohonan penerbitan BPKB (untuk kehilangan BPKPB)",
  "Surat keterangan ahli waris",
  "surat pernyataan penghasilan untuk non formal",
  "surat keterangan domisili (lembaga berbadan hukum, lembaga berbadan usaha, lembaga non berbadan hukum dan lembaga non berbadan usaha"
];

export const KELURAHAN_INFO = {
  name: "Kelurahan Kedung Baruk",
  address: "Jl. Raya Kedung Asem No. 59 Surabaya, Surabaya, Jawa Timur, Indonesia",
  phone: "(031) 8781191",
  email: "kel_kedungbaruk@surabaya.go.id",
};

export const DEFAULT_SETTINGS = {
  link_kng: "https://example.com/kng",
  link_sswalfa: "https://example.com/sswalfa",
};